# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
# This workflow will protect the main branch by testing and linting new PRs and commits

name: Main PR

# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16, 18]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    name: test - node.js ${{ matrix.node-version }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci --package-lock
      - run: npm test
        env:
          HANA_DB_CREDENTIALS: ${{secrets.HANA_DB_CREDENTIALS}}

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - run: npm ci --package-lock
      - run: npm run lint:ci
