# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
# This workflow will protect the main branch by testing and linting new PRs and commits

name: Main CI
permissions:
  contents: read
  pull-requests: write

# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#push
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20, 22, 24]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    name: test - node.js ${{ matrix.node-version }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm ci
      - run: npm test
        env:
          HANA_DB_CREDENTIALS: ${{secrets.HANA_DB_CREDENTIALS}}

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: npm
      - run: npm ci
      - run: npm run lint:ci
